title: Blog
description: Mi blog personal
author: Saúl Gausin
github: https://github.com/SaulG
about: Software Engineer and Master's student at CINVESTAV; I'm interested in data science, IoT and AI.
disqus_shortname: saulgausin
google_analytics: UA-137052982-1
avatar_url: https://avatars2.githubusercontent.com/u/1079432?s=400&u=3fa782dbfbea01bea4bd47902e9383c0b0dc2537&v=4

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/saulgausin"
    - icon: fa-stack-exchange
      link: "https://stackexchange.com/users/2493669/saul"
    - icon: fa-github
      link: "https://github.com/SaulG"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://saulg.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
